package com.vucic.coursematerials.lesson_4;

import com.vucic.coursematerials.R;

import java.util.ArrayList;
import java.util.List;

public class BookRepository {
    public static List<Book> getAllBooks() {
        List<Book> list = new ArrayList<>();
        list.add(new Book("Philosophiæ Naturalis Principia Mathematica", "Isaac Newton",
                "Presents Newton's unifying idea of gravitation and explains how he converted physics from a science of explanation into a general mathematical system.",
                "1687", R.drawable.lesson_4_book_1));
        list.add(new Book("Cosmos", "Carl Sagan",
                "* Spacecraft missions to nearby planets * The Library of ancient Alexandria * The human brain * Egyptian hieroglyphics * The origin of life * The death of the sun * The evolution of galaxies * The origins of matter, suns and worlds The story of fifteen billion years of cosmic evolution transforming matter and life into consciousness, of how science and civilisation grew up together, and of the forces and individuals who helped shape modern science. A story told with Carl Sagan's remarkable ability to make scientific ideas both comprehensible and exciting.",
                "1980", R.drawable.lesson_4_book_2));
        list.add(new Book("Thinking, Fast and Slow", "Daniel Kahneman",
                "NEW YORK TIMES BESTSELLER Two systems drive the way we think and make choices, Daniel Kahneman explains: System One is fast, intuitive, and emotional; System Two is slower, more deliberative, and more logical. Examining how both systems function within the mind, Kahneman exposes the extraordinary capabilities as well as the biases of fast thinking and the pervasive influence of intuitive impressions on our thoughts and our choices. Engaging the reader in a lively conversation about how we think, he shows where we can trust our intuitions and how we can tap into the benefits of slow thinking, contrasting the two-system view of the mind with the standard model of the rational economic agent. Kahneman's singularly influential work has transformed cognitive psychology and launched the new fields of behavioral economics and happiness studies. In this path-breaking book, Kahneman shows how the mind works, and offers practical and enlightening insights into how choices are made in both our business and personal lives--and how we can guard against the mental glitches that often get us into trouble.",
                "2011", R.drawable.lesson_4_book_2));
        list.add(new Book("The Count of Monte Cristo", "Alexandre Dumas",
                "Sent to prison on a false accusation in 1815, Edmond Dantes escapes many years later and finds a treasure which he uses to exact his revenge.",
                "1844-1846", R.drawable.lesson_4_book_4));
        list.add(new Book("The Hitchhiker's Guide to the Galaxy", "Douglas Adams",
                "Chronicles the off-beat and occasionally extraterrestrial journeys, notions, and acquaintances of galactic traveler Arthur Dent",
                "1978-1980", R.drawable.lesson_4_book_5));
        list.add(new Book("On the Origin of Species", "Charles Darwin",
                "Charles Darwin’s classic that exploded into public controversy, revolutionized the course of science, and continues to transform our views of the world. Few other books have created such a lasting storm of controversy as The Origin of Species. Darwin’s theory that species derive from other species by a gradual evolutionary process and that the average level of each species is heightened by the “survival of the fittest” stirred up popular debate to fever pitch. Its acceptance revolutionized the course of science. As Sir Julian Huxley, the noted biologist, points out in his illuminating introduction, the importance of Darwin’s contribution to modern scientific knowledge is almost impossible to evaluate: “a truly great book, one which can still be read with profit by professional biologist.",
                "1859", R.drawable.lesson_4_book_6));
        list.add(new Book("Behave", "Robert Sapolsky",
                "The New York Times Bestseller “It’s no exaggeration to say that Behave is one of the best nonfiction books I’ve ever read.” —David P. Barash, The Wall Street Journal \\\"It has my vote for science book of the year.” —Parul Sehgal, The New York Times \\\"Hands-down one of the best books I’ve read in years. I loved it.\\\" —Dina Temple-Raston, The Washington Post Named a Best Book of the Year by The Washington Post and The Wall Street Journal From the celebrated neurobiologist and primatologist, a landmark, genre-defining examination of human behavior, both good and bad, and an answer to the question: Why do we do the things we do? Sapolsky's storytelling concept is delightful but it also has a powerful intrinsic logic: he starts by looking at the factors that bear on a person's reaction in the precise moment a behavior occurs, and then hops back in time from there, in stages, ultimately ending up at the deep history of our species and its evolutionary legacy. And so the first category of explanation is the neurobiological one. A behavior occurs--whether an example of humans at our best, worst, or somewhere in between. What went on in a person's brain a second before the behavior happened? Then Sapolsky pulls out to a slightly larger field of vision, a little earlier in time: What sight, sound, or smell caused the nervous system to produce that behavior? And then, what hormones acted hours to days earlier to change how responsive that individual is to the stimuli that triggered the nervous system? By now he has increased our field of vision so that we are thinking about neurobiology and the sensory world of our environment and endocrinology in trying to explain what happened. Sapolsky keeps going: How was that behavior influenced by structural changes in the nervous system over the preceding months, by that person's adolescence, childhood, fetal life, and then back to his or her genetic makeup? Finally, he expands the view to encompass factors larger than one individual. How did culture shape that individual's group, what ecological factors millennia old formed that culture? And on and on, back to evolutionary factors millions of years old. The result is one of the most dazzling tours d'horizon of the science of human behavior ever attempted, a majestic synthesis that harvests cutting-edge research across a range of disciplines to provide a subtle and nuanced perspective on why we ultimately do the things we do...for good and for ill. Sapolsky builds on this understanding to wrestle with some of our deepest and thorniest questions relating to tribalism and xenophobia, hierarchy and competition, morality and free will, and war and peace. Wise, humane, often very funny, Behave is a towering achievement, powerfully humanizing, and downright heroic in its own right.",
                "2017", R.drawable.lesson_4_book_7));
        list.add(new Book("A Short History of Nearly Everything", "Bill Bryson",
                "The author of A Walk in the Woods traces the Big Bang through the rise of civilization, documenting his work with a host of the world's most advanced scientists and mathematicians to explain why things are the way they are. 125,000 first printing.",
                "2005", R.drawable.lesson_4_book_8));
        list.add(new Book("The Selfish Gene", "Richard Dawkins",
                "The Selfish Gene is a classic exposition of evolutionary thought. In it Professor Dawkins articulates a gene's eye view of evolution - a view giving centre stage to these persistent units of information, and in which organisms can be seen as vehicles for the replication of genes. The book provoked widespread and heated debate, which in part led Dawkins to write The Extended Phenotype, in which he gave a deeper clarification of the central concept of the gene as the unit of selection, as well as contributing his own development of this insight. For the first time, The Extended Selfish Gene brings these two books together, by including two key chapters from The Extended Phenotype. These chapters provide Dawkins's detailed and powerful response to two issues raised by critics of The Selfish Gene: the accusations of genetic determinism (the idea that our behaviour is entirely determined by our genes), and of \\\"adaptationism\\\" (that all traits are indiscriminately perceived to be adaptations resulting from natural selection). While written in particular for the biology community, Dawkins's clarity of expression allows these chapters to be accessible to all who are seriously engaged with the gene's eye view and its implications. The imaginative, powerful, and stylistically brilliant Selfish Gene not only brought the insights of Neo-Darwinism to a wide audience, but galvanized the biology community, generating much debate and stimulating whole new areas of research. Forty years later, its insights remain as significant as on the day it was published. Along with the two extra chapters, The Extended Selfish Gene includes a new epilogue to The Selfish Gene from the author which highlights the relevance of the gene's eye view to evolutionary biology today.",
                "", R.drawable.lesson_4_book_9));
        list.add(new Book("Lifespan: Why We Age – and Why We Don't Have To", "David A. Sinclair",
                "A NEW YORK TIMES BESTSELLER “Brilliant and enthralling.”\\u200b —The Wall Street Journal A paradigm-shifting book from an acclaimed Harvard Medical School scientist and one of Time’s most influential people. It’s a seemingly undeniable truth that aging is inevitable. But what if everything we’ve been taught to believe about aging is wrong? What if we could choose our lifespan? In this groundbreaking book, Dr. David Sinclair, leading world authority on genetics and longevity, reveals a bold new theory for why we age. As he writes: “Aging is a disease, and that disease is treatable.” This eye-opening and provocative work takes us to the frontlines of research that is pushing the boundaries on our perceived scientific limitations, revealing incredible breakthroughs—many from Dr. David Sinclair’s own lab at Harvard—that demonstrate how we can slow down, or even reverse, aging. The key is activating newly discovered vitality genes, the descendants of an ancient genetic survival circuit that is both the cause of aging and the key to reversing it. Recent experiments in genetic reprogramming suggest that in the near future we may not just be able to feel younger, but actually become younger. Through a page-turning narrative, Dr. Sinclair invites you into the process of scientific discovery and reveals the emerging technologies and simple lifestyle changes—such as intermittent fasting, cold exposure, exercising with the right intensity, and eating less meat—that have been shown to help us live younger and healthier for longer. At once a roadmap for taking charge of our own health destiny and a bold new vision for the future of humankind, Lifespan will forever change the way we think about why we age and what we can do about it.",
                "2019", R.drawable.lesson_4_book_10));
        return list;
    }
}
